Tests: do not depend on unexported constructors (manually)
Gemini wants to extend the export list:

Prompt:

Das Kompiliert nicht:

[4 of 5] Compiling Bottle.LogicSpec ( test/Bottle/LogicSpec.hs, /home/johannes/src/Decanter/dist-newstyle/build/x86_64-linux/ghc-9.8.4/decanter-0.1.0.0/t/decanter-test/build/decanter-test/decanter-test-tmp/Bottle/LogicSpec.o )

test/Bottle/LogicSpec.hs:46:41: error: [GHC-88464]
    Data constructor not in scope: EmptyName :: NameValid
   |
46 |         checkNameValidity "" `shouldBe` EmptyName
   |                                         ^^^^^^^^^

test/Bottle/LogicSpec.hs:49:48: error: [GHC-88464]
    Data constructor not in scope: ContainsSlash :: NameValid
   |
49 |         checkNameValidity "Hack/Me" `shouldBe` ContainsSlash
   |                                                ^^^^^^^^^^^^^

test/Bottle/LogicSpec.hs:50:52: error: [GHC-88464]
    Data constructor not in scope: ContainsSlash :: NameValid
   |
50 |         checkNameValidity "/RootBottle" `shouldBe` ContainsSlash
   |                                                    ^^^^^^^^^^^^^

test/Bottle/LogicSpec.hs:54:47: error: [GHC-88464]
    Data constructor not in scope: NameTooLong :: NameValid
   |
54 |         checkNameValidity longName `shouldBe` NameTooLong
   |

Response:

Das Problem liegt darin, dass in `Bottle/Logic.hs` nur der `Valid`-Konstruktor des Typs `NameValid` exportiert wurde, aber nicht die anderen Konstruktoren (`EmptyName`, `ContainsSlash`, `NameTooLong`), die im Test verwendet werden.

Ich habe die Export-Liste von `NameValid(Valid)` zu `NameValid(..)` geändert, damit alle Konstruktoren verfügbar sind.

Hier ist die korrigierte Datei: