Fix: more GTK4 changes by Gemini V3
Prompt:

Ich habe die Datei leicht angepasst, um einfachere Kompilierfehler zu lösen (s. O.). Ich bekomme aber immer noch Fehler, die nicht so leicht zu fixen scheinen:

```
[4 of 7] Compiling Gui.NewBottleDialog ( Gui/NewBottleDialog.hs, /home/johannes/src/haskell-bottles/dist-newstyle/build/x86_64-linux/ghc-9.8.4/haskell-bottles-0.1.0.0/x/haskell-bottles/build/haskell-bottles/haskell-bottles-tmp/Gui/NewBottleDialog.o ) [Source file changed]

Gui/NewBottleDialog.hs:38:7: error: [GHC-64725]
    • Unknown method ‘removeCssClass’ for type ‘Gtk.StyleContext’.
    • In the expression: #removeCssClass
      In a stmt of a 'do' block:
        #removeCssClass styleContext (T.pack "error")
      In the expression:
        do #setSensitive createBtn True
           styleContext <- #getStyleContext entryRow
           #removeCssClass styleContext (T.pack "error")
   |
38 |       #removeCssClass styleContext (T.pack "error") 
   |       ^^^^^^^^^^^^^^^

Gui/NewBottleDialog.hs:44:7: error: [GHC-64725]
    • Unknown method ‘addCssClass’ for type ‘Gtk.StyleContext’.
    • In the expression: #addCssClass
      In a stmt of a 'do' block:
        #addCssClass styleContext (T.pack "error")
      In the expression:
        do #setSensitive createBtn False
           styleContext <- #getStyleContext entryRow
           #addCssClass styleContext (T.pack "error")
   |
44 |       #addCssClass styleContext (T.pack "error") 
   |       ^^^^^^^^^^^^

Gui/NewBottleDialog.hs:91:10: error: [GHC-64725]
    • Unknown signal ‘notifyText’ for object ‘Adw.EntryRow’.
    • In the first argument of ‘($)’, namely ‘on nameEntry #notifyText’
      In the second argument of ‘($)’, namely
        ‘on nameEntry #notifyText $ validateName nameEntry createBtn’
      In a stmt of a 'do' block:
        void $ on nameEntry #notifyText $ validateName nameEntry createBtn
   |
91 |   void $ Gtk.on nameEntry #notifyText $ validateName nameEntry createBtn
   |          ^^^^^^

Gui/NewBottleDialog.hs:91:41: error: [GHC-64725]
    • Unknown signal ‘notifyText’ for object ‘Adw.EntryRow’.
    • In the second argument of ‘($)’, namely
        ‘validateName nameEntry createBtn’
      In the second argument of ‘($)’, namely
        ‘on nameEntry #notifyText $ validateName nameEntry createBtn’
      In a stmt of a 'do' block:
        void $ on nameEntry #notifyText $ validateName nameEntry createBtn
   |
91 |   void $ Gtk.on nameEntry #notifyText $ validateName nameEntry createBtn
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build exe:haskell-bottles from
haskell-bottles-0.1.0.0.
```

Response:

Das sind ausgezeichnete Compiler-Fehlermeldungen! Sie weisen auf zwei häufige Probleme bei der Arbeit mit der Haskell GObject Introspection (GI) Bibliothek hin, insbesondere im Hinblick auf unterschiedliche GTK-Versionen (GTK3 vs. GTK4) und die korrekte Verwendung von Signal-Handlern.

Hier ist die Analyse und die korrigierte Fassung Ihrer Datei Gui/NewBottleDialog.hs.
1. 🐞 Fehler: Unknown method ‘removeCssClass’/‘addCssClass’

Dieser Fehler tritt auf, weil Sie wahrscheinlich eine neuere GTK-Version (GTK4) verwenden, während die Methodennamen (#removeCssClass, #addCssClass) für GTK3 oder ältere Versionen des Haskell-Bindings typisch waren.

In GTK4 wurden diese Funktionen auf der Gtk.StyleContext-Ebene durch die Methoden auf der Gtk.Widget-Ebene ersetzt, und man arbeitet direkt mit den CSS-Klassen des Widgets.

Lösung:

Wir müssen styleContext <- #getStyleContext entryRow entfernen und stattdessen direkt die Methoden Gtk.widgetRemoveCssClass und Gtk.widgetAddCssClass (oder ihre gebundenen Varianten) verwenden, die auf das Widget selbst angewendet werden.
2. 🐞 Fehler: Unknown signal ‘notifyText’

Dieser Fehler ist ein Missverständnis der Syntax des Haskell-GI-Bindings für Eigenschafts-Benachrichtigungen (notify::).

Die korrekte Funktion in GI.Gtk für das Verbinden mit einem Benachrichtigungssignal ist Gtk.on, aber das Signal selbst muss als Text-Literal angegeben werden, und zwar als volle Eigenschafts-Benachrichtigung: T.pack "notify::text" (oder mit dem OverloadedStrings Pragmat on nameEntry $ Gtk.signalConnect "notify::text" ...).

Lösung:

Wir verwenden die Methode Gtk.on mit dem vollen Signalnamen als String: Gtk.on nameEntry (Gtk.signalConnect "notify::text") ....
🚀 Korrigierter Code (Gui/NewBottleDialog.hs)

<code omitted>

Diese Korrekturen sollten die Kompilierfehler beheben, indem sie:

    Die CSS-Klassen-Methoden auf die GTK4-konforme Weise (Gtk.widgetAddCssClass/Gtk.widgetRemoveCssClass) ändern.

    Das notify::text-Signal korrekt mit Gtk.signalConnect "notify::text" und einer kleinen Lambda-Wrapper-Funktion verbinden.

Möchten Sie, dass ich Ihnen erkläre, wie Sie diese Lambda-Wrapper vermeiden können, indem Sie eine leicht andere validateName-Signatur verwenden?